export const SET_COMMENTS_BY_FILE_ID = 'SET_COMMENTS_BY_FILE_ID';
export const SET_LIMITED_COMMENTS_BY_FILE_ID = 'SET_COMMENTS_BY_FILE_ID';
export const SET_TOTAL_COMMENTS_COUNT = 'SET_TOTAL_COMMENTS_COUNT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const UPDATE_COMMENT_REACTIONS = 'UPDATE_COMMENT_REACTIONS';

// const SET_COMMENTS = "setComments";

// export { SET_COMMENTS };